on:
  push:
    branches: [main]
  schedule:
  - cron: 0 4 * * 6
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: ./set-delete-branch-on-merge
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
